# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poma < Formula
  desc "CLI for the POMA AI API"
  homepage "https://github.com/poma-ai/poma-cli"
  version "0.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.15/poma-cli_0.1.15_darwin_amd64.tar.gz"
      sha256 "282dd9c2cc4b26e1e0a8ef6329b53e9b88eef50f56d6be637970114a2b17f3e6"

      define_method(:install) do
        bin.install "poma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.15/poma-cli_0.1.15_darwin_arm64.tar.gz"
      sha256 "84ea82181197aca9a1817edf5461d82e87d68aecb670f7a10a31e233cf763c63"

      define_method(:install) do
        bin.install "poma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.15/poma-cli_0.1.15_linux_amd64.tar.gz"
      sha256 "f1617cf1651a6f97b9a7e550a27afb890fec6c47b669ed9dd9bca1cc12c32d9e"
      define_method(:install) do
        bin.install "poma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.15/poma-cli_0.1.15_linux_arm64.tar.gz"
      sha256 "986ab776bff2051a35f418e6333a335c9994c6d68591846b4d69274efd6fc725"
      define_method(:install) do
        bin.install "poma"
      end
    end
  end

  def post_install
    if OS.mac?
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{bin}/poma"
    end
  end

  def caveats
    <<~EOS
      Authenticated commands need a JWT: export POMA_API_KEY or use --token / --json.
    EOS
  end

  test do
    system "#{bin}/poma", "--help"
  end
end
