# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poma < Formula
  desc "CLI for the POMA AI API"
  homepage "https://github.com/poma-ai/poma-cli"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.9/poma-cli_0.1.9_darwin_amd64.tar.gz"
      sha256 "57caa5a1591c08613a32816d208c01965c9a5890158fb897aee30b2c606c6428"

      define_method(:install) do
        bin.install "poma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.9/poma-cli_0.1.9_darwin_arm64.tar.gz"
      sha256 "b812c877da4826357df40ed9563f694950ae325009bc746bc1cdf7662cf952e9"

      define_method(:install) do
        bin.install "poma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.9/poma-cli_0.1.9_linux_amd64.tar.gz"
      sha256 "7ef4d8416cb5f55d28319cce90dfeccfa7f9cceab6e8f491b56ac2b5d5d59719"
      define_method(:install) do
        bin.install "poma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.9/poma-cli_0.1.9_linux_arm64.tar.gz"
      sha256 "186466c8960f448e27286ae901f6659a53a59e88715d9217dc117d5ac6856d6f"
      define_method(:install) do
        bin.install "poma"
      end
    end
  end

  def post_install
    if OS.mac?
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{bin}/poma"
    end
  end

  def caveats
    <<~EOS
      Authenticated commands need a JWT: export POMA_API_TOKEN or use --token / --json.
    EOS
  end

  test do
    system "#{bin}/poma", "--help"
  end
end
