# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poma < Formula
  desc "CLI for the POMA AI API"
  homepage "https://github.com/poma-ai/poma-cli"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.11/poma-cli_0.1.11_darwin_amd64.tar.gz"
      sha256 "2121545927a513a8860b0247e58910ca53d63221c3cf5692054aa6c0d35895f2"

      define_method(:install) do
        bin.install "poma"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.11/poma-cli_0.1.11_darwin_arm64.tar.gz"
      sha256 "91df87e27d217c1a82f55932e53889267f984fc4f736b07425c327a16c416a0b"

      define_method(:install) do
        bin.install "poma"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.11/poma-cli_0.1.11_linux_amd64.tar.gz"
      sha256 "7e09bb752feadf54052c65fac8e5c83658f5429823cbab739ebece47a1b5292a"
      define_method(:install) do
        bin.install "poma"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/poma-ai/poma-cli/releases/download/v0.1.11/poma-cli_0.1.11_linux_arm64.tar.gz"
      sha256 "063b183b2d1ee1089cf47b9b141201f723b214cfc57295937b499b2c076f7aaf"
      define_method(:install) do
        bin.install "poma"
      end
    end
  end

  def post_install
    if OS.mac?
      system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{bin}/poma"
    end
  end

  def caveats
    <<~EOS
      Authenticated commands need a JWT: export POMA_API_KEY or use --token / --json.
    EOS
  end

  test do
    system "#{bin}/poma", "--help"
  end
end
